### ISSUE TITLE
NS 4 - iOS - App crash because of algolia plugin

### ISSUE THREAD

**Issue by RaphaelJenni** [arpit2438735/nativescript-algolia#9] opened 2018-05-31 09:20 UTC
My App is running on NativeScript 4.0.
A lot of times the app crashes because of the algolia plugin. There is no error log.
I really don't know what the issue is, but it would be nice if it would be stable.
Maybe update the plugin to the new official plugin style, and add support for Angular.

Infos:
Nativescript 4.0
Angular 5.2.10
Algolia 0.0.4

**Comment by anuragd7** [comment] 2018-05-31 16:44
@arpit2438735 
I am running nativescript 3.4 and we too are experiencing quite a few crashes related to the algolia search. l am sharing some logs from crashlytics below
Request you to take a look

```
Fatal Exception: com.tns.NativeScriptException
Calling js method requestCompleted failed TypeError: Cannot read property 'results' of null File: "file:///data/data/org.nativescript.qbank/files/app/bundle.js, line: 1, column: 525653 StackTrace: Frame: function:'', file:'file:///data/data/org.nativescript.qbank/files/app/bundle.js', line: 1, column: 525654 Frame: function:'requestCompleted', file:'file:///data/data/org.nativescript.qbank/files/app/bundle.js', line: 1, column: 695885
arrow_right
com.tns.Runtime.callJSMethodNative (Runtime.java)
com.tns.Runtime.dispatchCallJSMethodNative (Runtime.java:1088)
com.tns.Runtime.callJSMethodImpl (Runtime.java:970)
com.tns.Runtime.callJSMethod (Runtime.java:957)
com.tns.Runtime.callJSMethod (Runtime.java:941)
com.tns.Runtime.callJSMethod (Runtime.java:933)
com.tns.gen.com.algolia.search.saas.CompletionHandler.requestCompleted (CompletionHandler.java:12)
com.algolia.search.saas.AbstractClient$AsyncTaskRequest$1.onPostExecute (AbstractClient.java:702)
com.algolia.search.saas.AbstractClient$AsyncTaskRequest$1.onPostExecute (AbstractClient.java:688)
android.os.AsyncTask.finish (AsyncTask.java:651)
```
Let me know if you need more information.

**Comment by arpit2438735** [comment] 2018-06-04 10:22
@RaphaelJenni @anuragd7 I will have a look into it.Locally I will update my nativescript to 4 and will let you know ASAP

**Comment by arpit2438735** [comment] 2018-06-04 13:45
@RaphaelJenni @anuragd7 I update my Nativescript Cli to 4 but still I didn't get any crashes locally for iOS.Can you guys elaborate more in what scenario it's failing or what user pattern you are using and causing an application to fail?

**Comment by anuragd7** [comment] 2018-06-04 15:55
@arpit2438735 , The crash does not happen consistently, in fact on most occasions I wont get a crash but then suddenly one search will return a crash. 
Here is one scenario in which I see the app failing sometimes. replicated below is an Algolia search function from my search service.

```
  public getSearchResult(value: string) {
    const queries = [
      {
        indexName: "XXXXXXX",
        query: value,
        params: {
          page: 0,
          hitsPerPage: 20
        }
      }
    ];
    this.client.search(queries, (success, error) => {
      const self = this;
      if (success) {
        self.myArray = [];
        const pageDetail = {};
        self.searchStatusService.setTotalSearchResults(
          success.results[0].nbHits
        );
        success.results[0].hits.forEach(element => {
          self.processEachItem(element);
        });
        if (success.results[0].hits.length >= success.results[0].hitsPerPage) {
          pageDetail["pageNo"] = 1;
          pageDetail["isLastPage"] = false;
        } else {
          pageDetail["pageNo"] = 0;
          pageDetail["isLastPage"] = true;
        }
        self.setSearchCurrentPageDetail(pageDetail);
        self.searchStatusService.setSearchResult(this.myArray);
        if (self.myArray.length <= 0) {
          self.searchResultx.emit({
            searchResult: self.myArray,
            status: "None",
            origin: "Normal"
          });
        } else {
          self.searchResultx.emit({
            searchResult: self.myArray,
            status: "Success",
            origin: "Normal"
          });
        }
      }
    });
  }

```

 Sometimes on executing a search I get the error posted below (reproduced from crashlytics): 

```
Fatal Exception: com.tns.NativeScriptException
Calling js method requestCompleted failed TypeError: Cannot read property 'results' of null File: "file:///data/data/org.nativescript.qbank/files/app/bundle.js, line: 1, column: 525653 StackTrace: Frame: function:'', file:'file:///data/data/org.nativescript.qbank/files/app/bundle.js', line: 1, column: 525654 Frame: function:'requestCompleted', file:'file:///data/data/org.nativescript.qbank/files/app/bundle.js', line: 1, column: 695885
arrow_right
com.tns.Runtime.callJSMethodNative (Runtime.java)
com.tns.Runtime.dispatchCallJSMethodNative (Runtime.java:1088)
com.tns.Runtime.callJSMethodImpl (Runtime.java:970)
com.tns.Runtime.callJSMethod (Runtime.java:957)
com.tns.Runtime.callJSMethod (Runtime.java:941)
com.tns.Runtime.callJSMethod (Runtime.java:933)
com.tns.gen.com.algolia.search.saas.CompletionHandler.requestCompleted (CompletionHandler.java:12)
com.algolia.search.saas.AbstractClient$AsyncTaskRequest$1.onPostExecute (AbstractClient.java:702)
com.algolia.search.saas.AbstractClient$AsyncTaskRequest$1.onPostExecute (AbstractClient.java:688)
android.os.AsyncTask.finish (AsyncTask.java:651)

```

**Comment by arpit2438735** [comment] 2018-06-05 06:35
@anuragd7 Looks like there's no data coming from algolia and it throw an error, still it's going in success callback, ideally it should went to error callback.That why there's no `results` object inside `success`

**Comment by anuragd7** [comment] 2018-06-05 06:38
I agree. That's what it seems like. Any suggestions?

**Comment by arpit2438735** [comment] 2018-06-05 07:10
I will try to add a fix.Meanwhile if you want to do a quick fix then just add one more condition

`if(success && success.results.length >0) //this condition will work`

**Comment by anuragd7** [comment] 2018-06-05 07:36
Thanks Arpit. Am doing that now.

**Comment by arpit2438735** [comment] 2018-06-11 05:14
@anuragd7 Does above solution works for you?

**Comment by anuragd7** [comment] 2018-06-11 05:22
Hi arpit,
Haven't had the search crash reported since i deployed. So far, so good.
Thanks

**Comment by arpit2438735** [comment] 2018-06-11 05:57
Cool.I will marked as closed.If you face any issue.Don't hesitate to open it again 👍

**Closed as completed** 2018-06-11 05:57 UTC
Labels: question
